customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    output: terminal
# gui:
#   theme:
#     activeBorderColor:
#       - "#83a598" # bright_blue
#       - bold
#     inactiveBorderColor:
#       - "#928374" # gray
#     optionsTextColor:
#       - "#83a598" # bright_blue
#     selectedLineBgColor:
#       - "#504945" # dark2
#     selectedRangeBgColor:
#       - "#665c54" # dark3
#     cherryPickedCommitBgColor:
#       - "#7b2c2f" # dark_red_soft
#     cherryPickedCommitFgColor:
#       - "#fabd2f" # bright_yellow
#     unstagedChangesColor:
#       - "#fb4934" # bright_red
#     defaultFgColor:
#       - "#ebdbb2" # light1
#     searchingActiveBorderColor:
#       - "#fabd2f" # bright_yellow
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# cyberdream theme for lazygit
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
# # yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# # cyberdream theme for lazygit
# gui:
#     border: rounded
#     theme:
#         activeBorderColor:
#             - "#008c99"
#         inactiveBorderColor:
#             - "#7b8496"
#         searchingActiveBorderColor:
#             - "#d100bf"
#         optionsTextColor:
#             - "#acacac"
#         selectedLineBgColor:
#             - "#acacac"
#         cherryPickedCommitBgColor:
#             - "#acacac"
#         cherryPickedCommitFgColor:
#             - "#f40064"
#         unstagedChangesColor:
#             - "#d17c00"
#         defaultFgColor:
#             - "#16181a"
git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
