[tools]
node = 'latest'
go = 'latest'
bun = 'latest'
uv = 'latest'
usage = "latest"
zig = 'latest'

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true
