window.padding = { x = 8, y = 4 }
window.decorations = "Buttonless"
terminal.shell = "/opt/homebrew/bin/fish"

general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

font.normal = { family = "JetBrainsMono Nerd Font" }
font.size = 14

scrolling.history = 100000
